//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martin.SQLServer.Dts.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Martin.SQLServer.Dts.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime version of MultipleHash is out of date - please install the upgrade....
        /// </summary>
        internal static string BadRuntimeVersion {
            get {
                return ResourceManager.GetString("BadRuntimeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary data types not supported..
        /// </summary>
        internal static string BinaryDataTypesNotSupported {
            get {
                return ResourceManager.GetString("BinaryDataTypesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error %s thrown when checking LineageID.
        /// </summary>
        internal static string ColumnLineageIDInvalid {
            get {
                return ResourceManager.GetString("ColumnLineageIDInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component .
        /// </summary>
        internal static string Component {
            get {
                return ResourceManager.GetString("Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DT_DBDATE data type is not supported..
        /// </summary>
        internal static string DBDateDataTypeNotSupported {
            get {
                return ResourceManager.GetString("DBDateDataTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DT_FILETIME data type is not supported..
        /// </summary>
        internal static string DBFileTimeDataTypeNotSupported {
            get {
                return ResourceManager.GetString("DBFileTimeDataTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DT_DBTIME data type is not supported..
        /// </summary>
        internal static string DBTimeDataTypeNotSupported {
            get {
                return ResourceManager.GetString("DBTimeDataTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There should be exactly one input.  The metadata of this component is corrupt..
        /// </summary>
        internal static string Exactly1Input {
            get {
                return ResourceManager.GetString("Exactly1Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There should be exactly one output. The metadata of this component is corrupt..
        /// </summary>
        internal static string Exactly1Output {
            get {
                return ResourceManager.GetString("Exactly1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MultiThread Property is missing..
        /// </summary>
        internal static string MultiThreadPropertyMissing {
            get {
                return ResourceManager.GetString("MultiThreadPropertyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all editing services available..
        /// </summary>
        internal static string NotAllEditingServicesAvailable {
            get {
                return ResourceManager.GetString("NotAllEditingServicesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  does not allow adding inputs..
        /// </summary>
        internal static string NotAllowAddingInputs {
            get {
                return ResourceManager.GetString("NotAllowAddingInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  does not allow adding outputs..
        /// </summary>
        internal static string NotAllowAddingOutputs {
            get {
                return ResourceManager.GetString("NotAllowAddingOutputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output columns cannot be added to .
        /// </summary>
        internal static string OutputColumnsCannotBeAdded {
            get {
                return ResourceManager.GetString("OutputColumnsCannotBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HashType and Column Data Types do not match..
        /// </summary>
        internal static string OutputDatatypeInvalid {
            get {
                return ResourceManager.GetString("OutputDatatypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output property that you selected, can not be changed..
        /// </summary>
        internal static string OutputPropertyCannotBeChanged {
            get {
                return ResourceManager.GetString("OutputPropertyCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output property HashType is set to an invalid value for column %s..
        /// </summary>
        internal static string PropertyHashTypeInvalid {
            get {
                return ResourceManager.GetString("PropertyHashTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output property HashType is missing from column %s..
        /// </summary>
        internal static string PropertyHashTypeMissing {
            get {
                return ResourceManager.GetString("PropertyHashTypeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output property InputColumnLineageIDs has invalid lineage id&apos;s for column %s..
        /// </summary>
        internal static string PropertyInputColumnLineageIDsInvalid {
            get {
                return ResourceManager.GetString("PropertyInputColumnLineageIDsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output property InputColumnLineageIDs is missing from column %s..
        /// </summary>
        internal static string PropertyInputColumnLineageIDsMissing {
            get {
                return ResourceManager.GetString("PropertyInputColumnLineageIDsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property MultiThread is set to an invalid value..
        /// </summary>
        internal static string PropertyMultiThreadInvalid {
            get {
                return ResourceManager.GetString("PropertyMultiThreadInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output properties HashType and InputColumnLineageIDs are missing from column %s..
        /// </summary>
        internal static string PropertyRemoved {
            get {
                return ResourceManager.GetString("PropertyRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read write not supported..
        /// </summary>
        internal static string ReadWriteNotSupported {
            get {
                return ResourceManager.GetString("ReadWriteNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are to many Multi Thread Properties Defined..
        /// </summary>
        internal static string ToManyMultiThreadProperties {
            get {
                return ResourceManager.GetString("ToManyMultiThreadProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UI is in an inconsistent state: Passed argument is not valid..
        /// </summary>
        internal static string UIisInconsistentState {
            get {
                return ResourceManager.GetString("UIisInconsistentState", resourceCulture);
            }
        }
    }
}
